#two Dockerfile write docker compose.yml file 
version: '3'
services:
  apache:
    build:
      context: .
      dockerfile: apache-Dockerfile
    ports:
      - "8002:80"

  static:
    build:
      context: .
      dockerfile: static-Dockerfile
    ports:
      - "8000:80"


#   =====================================

version: "3"
services:
  apache:
    image: "httpd"
    ports:
      - "8002:80"
  nginx:
    image: "nginx"
    ports:
      - "8003:80"


















# #!/bin/bash
# version: "3.9"
# services:
#   web:
#     image: latest
#     build:
#       context: ./
#       dockerfile: Dockerfile

# =====================================
# #!/bin/bash
#     services:
#     app:
#         container_name: app
#         image: latest
#         build:
#             context: .
#             dockerfile: Dockerfile
#         restart: always
#         ports:
#             - "8080:8080"
# =========================================


# docker-compose up -d
# docker-compose ps














